### ISSUE TITLE
Undefined operation % mod styled-jsx-placeholder-0

### ISSUE THREAD

**Issue by Tomekmularczyk** [giuseppeg/styled-jsx-plugin-sass#1]
Hey! Thanks for the plugin.

I have a test repo where I try to use this plugin but unfortunately, I get an error:

> Module build failed: Error: /Users/Praca/Desktop/Projekty/react-starter/src/app/pages/Page404.jsx: Undefined operation: "% mod styled-jsx-placeholder-0".
>     
> at module.exports.renderSync (/Users/Praca/Desktop/Projekty/react-starter/node_modules/node-sass/lib/index.js:439:16)
>     
> at module.exports (/Users/Praca/Desktop/Projekty/react-starter/node_modules/styled-jsx-plugin-sass/index.js:12:24)

...

[Here is the repo.](https://github.com/Tomekmularczyk/react-starter/tree/styled-jsx-sass)

**Comment by giuseppeg** [comment]
yup the plugin is a proof of concept, styled-jsx expressions are replaced with `%%styled-jsx-placeholder-0%%` which is not valid Sass, before preprocessing with sass those need to be replaced.. see the plugin source code. 

Please consider contributing to this plugin to fix this issue, since I don't have a lot of time to invest into it.

**Comment by giuseppeg** [comment]
Fixed by #3
