### ISSUE TITLE
imports inside jsx

### ISSUE THREAD

**Issue by lailo-ch** [giuseppeg/styled-jsx-plugin-sass#10]
Is it possible to import sass files inside the JSX like the following while having a file in the same folder named `_variables.scss`? 

```
import css from 'styled-jsx/css'

export default css`
  @import './variables';

  .hello {
    background-color: $color;
    padding: 200px;
    text-align: center;
    transition: 200ms ease-in background;
    color: blue;
    font-size: 40px;
    &:hover {
      color: $color;
    }
    @media only screen and (max-width: $max-screen) {
      font-size: 20px;
    }
  }
`
```

I want to be able to import bootstrap and overwrite some variables.
Thanks for helping.

**Comment by giuseppeg** [comment]
it should be possible, but I haven't tried :) let me know if it works!

**Comment by MarcoThePoro** [comment]
Hi I've experimented with this but it looks like relative imports are not yet possible.

Since the sass is compiled from a string, not a file, node-sass doesn't know where the source came from so can't resolve relative imports.

The file path should be added to `includePaths` when rendering the sass to allow relative imports, it's super simple and I tried to cook up a PR however currently the `styled-jsx` plugin system doesn't supply plugins with a file path.

For now, you can still specify `includePaths` in the `styled-jsx-plugin-sass` options.

**Comment by giuseppeg** [comment]
yep I guess that it should work via plugin/node-sass options  https://github.com/giuseppeg/styled-jsx-plugin-sass#node-sass-options
